import { expect, test } from "bun:test";

test("upstream scheduling V2 is a Codex-first read-only page", async () => {
  const html = await Bun.file(new URL("./upstream-scheduling-v2.html", import.meta.url)).text();
  const script = await Bun.file(new URL("./upstream-scheduling-v2.js", import.meta.url)).text();
  const app = await Bun.file(new URL("./app.js", import.meta.url)).text();
  expect(html).toContain("上游调度 V2");
  expect(html).toContain('data-page="upstream-scheduling-v2"');
  expect(html).toContain('id="v2-scope-switch"');
  expect(html).toContain('class="pool-quality-head"');
  expect(html).toContain('unified-quota-monitor');
  expect(html).toContain('class="pool-quality-band"');
  expect(html).toContain("unified-upstream-table");
  expect(html).toContain('id="v2-error-body"');
  expect(html).toContain('id="v2-history-body"');
  expect(html).toContain('id="v2-probe-body"');
  expect(html).toContain('id="v2-account-table"');
  expect(html).toContain('data-sort-key="score"');
  expect(html).toContain('data-sort-key="priority"');
  expect(html).not.toContain('id="v2-plan-table"');
  expect(html).not.toContain('只读优先级计划');
  expect(html).toContain('id="v2-automation-state"');
  expect(html).not.toContain("对账");
  expect(script).not.toContain("对账");
  expect(script).toContain("/api/v2/upstream-scheduling/scopes");
  expect(script).toContain("/api/v2/upstream-scheduling/snapshot");
  expect(script).not.toContain("/api/v2/upstream-scheduling/plan");
  expect(script).toContain("scopeRequestId");
  expect(script).toContain("state.activeScope !== scope");
  expect(script).toContain("new URLSearchParams(location.search)");
  expect(script).toContain("updateScopeDeepLink(state.activeScope, 'push')");
  expect(script).toContain("window.addEventListener('popstate'");
  expect(script).toContain("额度缓存");
  expect(script).toContain("不限额");
  expect(script).toContain("sampleTimeDisplay");
  expect(script).toContain("次采样");
  expect(script).toContain("bindTableSortHeaders");
  expect(script).toContain("sortTableRows");
  expect(script).not.toMatch(/method:\s*['"](?:POST|PUT|PATCH|DELETE)['"]/u);
  expect(app).toContain("upstream-scheduling-v2");
});
